#!/bin/bash

set -eo pipefail
env=$1

script_path=$(readlink -f "$0")
script_dir=$(dirname "$script_path")
cd "${script_dir}/hugo"

if [[ "$env" != 'dev' ]] && [[ "$env" != 'prod' ]]; then
	printf 'invalid environment: %s\n' "$env" >&2
	exit 1
fi

rm -rf 'public/'
hugo --environment "$env"
find 'public/' -name '*.xml' | grep -v blog | xargs rm -f
