---

services:
  dynamodb:
    image:   amazon/dynamodb-local:2.5.3
    command: "-jar /home/dynamodblocal/DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    ports:
      - 8000:8000
    volumes:
      - ./localdev/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal/data

  rsvp:
    image: golang:1.23-bookworm
    command: go run main.go
    ports:
      - 9000:9000
    volumes:
      - ./rsvp:/app
      - gopath:/go
    working_dir: /app
    environment:
      API_CLIENT_TOKEN: LOCAL_DEV_ONLY_cddfdfecd70f74a344691214047d5f8acc_LOCAL_DEV_ONLY
      API_SECRET_KEY:   LOCAL_DEV_ONLY_de1b1a3cdbacf260de3c1c28da86ae9e5b_LOCAL_DEV_ONLY
      DYNAMODB_INVITATIONS_TABLE: WeddingInvitations
      RSVP_LISTEN_ADDRESS: "0.0.0.0:9000"
    develop:
      watch:
        - action: restart
          path:   ./rsvp

volumes:
  gopath:
